eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8091
spring:
  application:
    name: consumer
  config:
    import: optional:configserver:http://localhost:8888
logging:
  level:
    root: INFO
    com.microservice.producer: DEBUG
  file:
    name: logs/history.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [CONSUMER] %-5level %logger{36} - %msg%n"